package com.testing;

import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.GraphWalker;

import java.io.IOException;


/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that com.testing.SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */

@GraphWalker(
        value = "random(edge_coverage(100))"
)

public class SomeSmallTest extends ExecutionContext implements ChuckModel {
    WebSocket webSocket = new WebSocket();

    public WebSocket getWebSocket() {
        return webSocket;
    }

    @Override
    public void e_Aleatorio() throws IOException{
        System.out.println("Running: e_Aleatorio");
        ClienteAPI clienteAPI = new ClienteAPI();
        ClienteAPI.request("https://api.chucknorris.io/jokes/random");
    }

    @Override
    public void v_VerCategorias() throws IOException{
        System.out.println("Running:v_VerCategorias");
        ClienteAPI clienteAPI = new ClienteAPI();
        ClienteAPI.request("https://api.chucknorris.io/jokes/categories");

    }
    @Override
    public void e_ElegirCategoria() throws IOException {
        System.out.println("Running: e_ElegirCategoria");
        ClienteAPI clienteAPI = new ClienteAPI();
        ClienteAPI.request("https://api.chucknorris.io/jokes/random?category=history");
    }

    @Override
    public void e_ListarCategorias() throws IOException {
        System.out.println("Running: e_ListarCategorias");
        ClienteAPI clienteAPI = new ClienteAPI();
        ClienteAPI.request("https://api.chucknorris.io/jokes/categories");
    }

    @Override
    public void v_VerChiste() throws IOException {
        System.out.println("Running: v_VerChiste");
        ClienteAPI clienteAPI = new ClienteAPI();
        ClienteAPI.request("https://api.chucknorris.io/jokes/categories");

    }
}
